### ISSUE TITLE
I need some help, please.

### ISSUE THREAD

**Issue by BaxAndrei** [nkomarn/harbor#43]
I installed this plugin on my server, and this is my config:

```
features:
  phantoms: false # Reset the sleep statistic (practically disables phantom spawns - false = no phantoms)
```
and phantoms still appears.

From what I saw (on line desc), if false = no phantoms, or might be true?
PS: I installed plugin ~a month after first server start

**Comment by nkomarn** [comment]
@baxandrei The phantom statistic is only reset for the online players when the night is skipped- that's how I implemented that feature in Harbor 1.6+. If you're running 1.15+, you can use `/gamerule doInsomnia false` to permanently disable Phantom spawning. Otherwise, reopen this issue and I will be able to re-implement the Harbor 1.5 phantom behavior.

**Comment by BaxAndrei** [comment]
It`s ok, thank you. And if I want to enable phantoms again just set `phantoms: true`?

**Comment by nkomarn** [comment]
> It`s ok, thank you. And if I want to enable phantoms again just set `phantoms: true`?

Correct!
