### ISSUE TITLE
Messages spammed players

### ISSUE THREAD

**Issue by viveleroi** [nkomarn/harbor#53]
We've been using Harbor fine for several days but it suddenly spammed message. Not sure I can provide any more info. Latest version for paper b273 for MC 1.15.2.

https://puu.sh/FJDjH/65333426a5.png

**Comment by nkomarn** [comment]
> We've been using Harbor fine for several days but it suddenly spammed message. Not sure I can provide any more info. Latest version for paper b273 for MC 1.15.2.
> 
> https://puu.sh/FJDjH/65333426a5.png

What Harbor version?

**Comment by viveleroi** [comment]
1.6.1

**Comment by nkomarn** [comment]
As far as I know, that's only an issue when it's thundering and you try to skip night since you can sleep during thunderstorms. Good news is- the latest beta releases of Harbor 1.6.2 have fixed this issue, and you can download the latest build [here](https://github.com/nkomarn/Harbor/releases/tag/1.6.2-b6). 

You will have to delete your old config file when updating since 1.6.2 has a new config format that is easier to read. Let me know if you have any other issues when using the beta.
