### ISSUE TITLE
Night skipping message gets spammed in chat

### ISSUE THREAD

**Issue by donvdp** [nkomarn/harbor#63]
Hi there,

it appears so that at random we will get a huge ammount to spam in chat when skipping the night..

this will look something like this:   [https://imgur.com/QdBEPDM](https://imgur.com/QdBEPDM)
The harbor config file looks like:   [https://pastebin.pl/view/7a0805f6](https://pastebin.pl/view/7a0805f6)

We are running harbor version 1.6.1 on paper MC build 99. But we have also experienced this on previous versions of papermc. 
Would you guys happen to have an idea what would be causing this night skip spam?

Kindly thanks for your reply

**Comment by nkomarn** [comment]
This is a possible edge case that can happen when it's thundering and the weather clearing feature is disabled, since people are able to continue sleeping even after the night has been skipped. Your config link isn't loading for me, but I am assuming you might have weather clearing disabled. 

The latest pre-release build of Harbor, which you can get from the releases section of this repository, should have fixed this issue. Just make sure to regenerate your configuration file if you plan to update to that version.

**Comment by donvdp** [comment]
you are correct. [this ](https://hastebin.com/azunibeyod.bash)is our config file. we have "weather: false". ill download the version 1.6.2 Beta 6 and run a fresh config file. ofcourse tweak that with our dutch language file, and try if this will fix it. i will report back if i have an update.

**Comment by donvdp** [comment]
works like a charm. thanks !
